before_install:
  - openssl aes-256-cbc -K $encrypted_a619f2099269_key -iv $encrypted_a619f2099269_iv
    -in key.asc.enc -out key.asc -d
  - gpg --import key.asc
  - curl -L -o ~/bin/mill "https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6" && chmod +x ~/bin/mill
  - PATH=~/bin/mill:$PATH

language: scala
jdk: openjdk8

stages:
  - name: test
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: test
      name: CLI build
      script: ./.ci_scripts/build_cli.sh
    - stage: test
      name: Core build (JVM/2.11)
      script: ./.ci_scripts/build_core.sh "jvm" "2.11.12"
    - stage: test
      name: Core build (JVM/2.12)
      script: ./.ci_scripts/build_core.sh "jvm" "2.12.8"
    - stage: test
      name: Core build (JS/2.11)
      script: ./.ci_scripts/build_core.sh "js" "2.11.12"
    - stage: test
      name: Core build (JS/2.12)
      script: ./.ci_scripts/build_core.sh "js" "2.12.8"
    - stage: publish
      script: ./.ci_scripts/publish.sh
