version: 2.1

executors:
  openjdk-8-node:
    docker:
      - image: guilgaly/openjdk-mill-node-heroku:8u181-0.3.6-stretch
    working_directory: /tmp/cowsay4s
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb

jobs:
  check-format:
    executor: openjdk-8-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-coursier-scalafmt-{{ checksum "dependencies.sc" }}
            - v2-coursier-scalafmt-
      - run: ./.circleci/check_formatting.sh
      - save_cache:
          key: v2-coursier-scalafmt-{{ checksum "dependencies.sc" }}
          paths:
            - ~/.cache/coursier
      - persist_to_workspace:
          root: /tmp
          paths:
            - cowsay4s
  test-publish:
    parameters:
      scala-flavor:
        type: string
      scala-version:
        type: string
      add-build:
        type: string
        default: ""
    executor: openjdk-8-node
    steps:
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - v2-coursier-<< parameters.scala-flavor >>-<< parameters.scala-version >>-{{ checksum "dependencies.sc" }}
            - v2-coursier-<< parameters.scala-flavor >>-<< parameters.scala-version >>-
      - run: ./.circleci/execute_tests.sh << parameters.scala-flavor >> << parameters.scala-version >> << parameters.add-build >>
      - run: ./.circleci/publish.sh << parameters.scala-flavor >> << parameters.scala-version >>
      - save_cache:
          key: v2-coursier-<< parameters.scala-flavor >>-<< parameters.scala-version >>-{{ checksum "dependencies.sc" }}
          paths:
            - ~/.cache/coursier

workflows:
  version: 2
  build:
    jobs:
      - check-format:
          name: "Scalafmt"

      - test-publish:
          name: "JVM 2.11"
          requires:
            - "Scalafmt"
          scala-flavor: "jvm"
          scala-version: "2.11.12"
      - test-publish:
          name: "JVM 2.12 + CLI"
          requires:
            - "Scalafmt"
          scala-flavor: "jvm"
          scala-version: "2.12.8"
          add-build: "cli"
      - test-publish:
          name: "JS 2.11"
          requires:
            - "Scalafmt"
          scala-flavor: "js"
          scala-version: "2.11.12"
      - test-publish:
          name: "JS 2.12"
          requires:
            - "Scalafmt"
          scala-flavor: "js"
          scala-version: "2.12.8"
