version: 2.1

executors:
  openjdk-8-node:
    docker:
      - image: guilgaly/openjdk-mill-node-heroku:8.0.242-0.6.1
    working_directory: /tmp/cowsay4s
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb
  openjdk-11-node:
    docker:
        - image: guilgaly/openjdk-mill-node-heroku:11.0.6-0.6.1
    working_directory: /tmp/cowsay4s
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb

jobs:
  build:
    parameters:
      executor:
        type: string
      scala-version:
        type: string
      add-build:
        type: string
        default: ""
      publish:
        type: boolean
        default: false
    executor:
      name: << parameters.executor >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-coursier-<< parameters.scala-version >>-{{ checksum "dependencies.sc" }}-{{ checksum "build.sc" }}
            - v2-coursier-<< parameters.scala-version >>-{{ checksum "dependencies.sc" }}
            - v2-coursier-<< parameters.scala-version >>-
      - run: ./.circleci/test.sh << parameters.scala-version >> << parameters.add-build >>
      - when:
          condition: << parameters.publish >>
          steps:
            - run: ./.circleci/publish.sh << parameters.scala-version >>
      - save_cache:
          key: v2-coursier-<< parameters.scala-version >>-{{ checksum "dependencies.sc" }}-{{ checksum "build.sc" }}
          paths:
            - ~/.cache/coursier

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: "2.12 (JDK 11)"
          executor: "openjdk-11-node"
          scala-version: "2.12.11"
      - build:
          name: "2.12 (JDK 8)"
          requires:
            - "2.12 (JDK 11)"
          executor: "openjdk-11-node"
          scala-version: "2.12.11"
          publish: true

      - build:
          name: "2.13 (JDK 11)"
          executor: "openjdk-11-node"
          scala-version: "2.13.1"
          add-build: "cli"
      - build:
          name: "2.13 (JDK 8)"
          requires:
            - "2.13 (JDK 11)"
          executor: "openjdk-11-node"
          scala-version: "2.13.1"
          add-build: "cli"
          publish: true
